name: teflink_http
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
