name: teflink_acore
description: A basic framework.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  teflink_core: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
