name: teflink_dot_env
description: .Env package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.17.2
