name: teflink_console
description: A sample command-line application.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  enough_ascii_art: ^1.0.0
  teflink_core: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
